
if GetLocale() == "deDE" then
	updateLocale(
{
	["Going To Need A Bigger Bag"] = "Schatz, ich brauche eine neue Tasche",
	--
	["Cursed Swabby Helmet"] = "Verfluchter Matrosenhelm",
	["Warped Warning Sign"] = "Verformtes Warnschild",
	["Giant Purse of Timeless Coins"] = "Gro\195\159er Beutel voll zeitloser M\195\188nzen",
	["Crystal of Insanity"] = "Kristall des Wahnsinns",
	["Battle Horn"] = "Schlachthorn",
	["Elixir of Ancient Knowledge"] = "Elixier des uralten Wissens",
	["Forager's Gloves"] = "Sammlerhandschuhe",
	["Big Bag of Herbs"] = "Gro\195\159er Sack voll Kr\195\164uter",
	["Big Bag of Herbs (Old)"] = "Gro\195\159er Sack voll Kr\195\164uter (Alt)",
	["Wilted Lilypad"] = "\195\156bergro\195\159es Seerosenblatt",
	["Hardened Shell"] = "Geh\195\164rteter Panzer",
	["Bubbling Pi'jiu Brew"] = "Blubberndes Pi'jiubr\195\164u",
	["Thick Pi'jiu Brew"] = "Dickfl\195\188ssiges Pi'jiubr\195\164u",
	["Misty Pi'jiu Brew"] = "Nebliges Pi'jiubr\195\164u",
	["Warning Sign"] = "Warnschild",
	["Ash-Covered Horn"] = "Aschebedecktes Horn",
	["Cauterizing Core"] = "Kauterisierender Kern",
	["Captain Zvezdan's Lost Leg"] = "Kapit\195\164n Zvezdans verlorenes Bein",
	["Cursed Talisman"] = "Verfluchter Talisman",
	["Golden Moss"] = "Goldenes Moos",
	["Strange Glowing Mushroom"] = "Merkw\195\188rdig leuchtender Pilz",
	["Eternal Kiln"] = "Ewiger Flammenkessel",
	["Jadefire Spirit"] = "Jadefeuergeist",
	["Sunset Stone"] = "Sonnenuntergangsstein",
	["Ashen Stone"] = "Aschestein",
	["Blizzard Stone"] = "Blizzardstein",
	["Rain Stone"] = "Regenstein",
	["Blackflame Daggers"] = "Schwarzflammendolche",
	["Falling Flame"] = "Flammenschnuppe",
	["Ordon Death Chime"] = "Totenglocke von Ordos",
	["Blazing Sigil of Ordos"] = "Leuchtendes Siegel von Ordos",
	["Ordon Ceremonial Robes"] = "Zeremonielle Roben von Ordos",
	["Rime of the Time-Lost Mariner"] = "Reif des zeitverlorenen Seefahrers",
	["Scuttler's Shell"] = "Krabblerpanzer",
	["Partially-Digested Meal"] = "Halbverdaute Mahlzeit",
	["Swarmling of Gu'chi"] = "Schwarmling von Gu'chi",
	["Sticky Silkworm Goo"] = "Klebriges Seidenraupenexkret",
	["Faintly-Glowing Herb"] = "Schwach leuchtendes Kraut",
	["Condensed Jademist"] = "Kondensierter Jadenebel",
	["Windfeather Plume"] = "Windfeder",
	["Quivering Firestorm Egg"] = "Zitterndes Feuersturmei",
	["Reins of the Thundering Onyx Cloud Serpent"] = "Z\195\188gel der donnernden Onyxwolkenschlange",
	["Pristine Stalker Hide"] = "Makelloser Pirscherbalg",
	["Glinting Pile of Stone"] = "Haufen glitzernder Steine",
	["Odd Polished Stone"] = "Seltsamer glatt geschliffener Stein",
	["Glowing Blue Ash"] = "Leuchtende blaue Asche",
	["Glowing Green Ash"] = "Leuchtende gr\195\188ne Asche",
	["Bonkers"] = "Flipps",
	["Gulp Froglet"] = "Schluckfroschling",
	["Spineclaw Crab"] = "Dornzangenkrabbe",
	["Skunky Alemental"] = "Ranziger Bierlementar",
	["Ominous Flame"] = "Omin\195\182se Flamme",
	["Jademist Dancer"] = "Jadenebelt\195\164nzer",
	["Death Adder Hatchling"] = "Todesnatterjungtier",
	["Dandelion Frolicker"] = "L\195\182wenzahnwitzbold",
	["Ruby Droplet"] = "Rubinrotes Tr\195\182pfchen",
	["Azure Crane Chick"] = "Azurblaues Kranichk\195\188ken",
	["Ashleaf Spriteling"] = "Eschenblattgeistling",
	---
	["Crane Nest"] = "Kranichnest",
	["Eerie Crystal"] = "Unheimlicher Kristall",
	["Sunken Treasure"] = "Versunkener Schatz",
	["Timeless Chest"] = "Zeitlose Truhe",
	----
	["missing"] = "fehlt",
	--["completed"] = "Abgeschlossen: ",
	["completed"] = "fertig",
}
)

end