

updateLocale(
{
	["Going To Need A Bigger Bag"] = true,
	--
	["Cursed Swabby Helmet"] = true,
	["Warped Warning Sign"] = true,
	["Giant Purse of Timeless Coins"] = true,
	["Crystal of Insanity"] = true,
	["Battle Horn"] = true,
	["Elixir of Ancient Knowledge"] = true,
	["Forager's Gloves"] = true,
	["Big Bag of Herbs"] = true,
	["Big Bag of Herbs (Old)"] = true,
	["Wilted Lilypad"] = true,
	["Hardened Shell"] = true,
	["Bubbling Pi'jiu Brew"] = true,
	["Thick Pi'jiu Brew"] = true,
	["Misty Pi'jiu Brew"] = true,
	["Warning Sign"] = true,
	["Ash-Covered Horn"] = true,
	["Cauterizing Core"] = true,
	["Captain Zvezdan's Lost Leg"] = true,
	["Cursed Talisman"] = true,
	["Golden Moss"] = true,
	["Strange Glowing Mushroom"] = true,
	["Eternal Kiln"] = true,
	["Jadefire Spirit"] = true,
	["Sunset Stone"] = true,
	["Ashen Stone"] = true,
	["Blizzard Stone"] = true,
	["Rain Stone"] = true,
	["Blackflame Daggers"] = true,
	["Falling Flame"] = true,
	["Ordon Death Chime"] = true,
	["Blazing Sigil of Ordos"] = true,
	["Ordon Ceremonial Robes"] = true,
	["Rime of the Time-Lost Mariner"] = true,
	["Scuttler's Shell"] = true,
	["Partially-Digested Meal"] = true,
	["Swarmling of Gu'chi"] = true,
	["Sticky Silkworm Goo"] = true,
	["Faintly-Glowing Herb"] = true,
	["Condensed Jademist"] = true,
	["Windfeather Plume"] = true,
	["Quivering Firestorm Egg"] = true,
	["Reins of the Thundering Onyx Cloud Serpent"] = true,
	["Pristine Stalker Hide"] = true,
	["Glinting Pile of Stone"] = true,
	["Odd Polished Stone"] = true,
	["Glowing Blue Ash"] = true,
	["Glowing Green Ash"] = true,
	["Bonkers"] = true,
	["Gulp Froglet"] = true,
	["Spineclaw Crab"] = true,
	["Skunky Alemental"] = true,
	["Ominous Flame"] = true,
	["Jademist Dancer"] = true,
	["Death Adder Hatchling"] = true,
	["Dandelion Frolicker"] = true,
	["Ruby Droplet"] = true,
	["Azure Crane Chick"] = true,
	["Ashleaf Spriteling"] = true,
	---
	["Crane Nest"] = true,
	["Eerie Crystal"] = true,
	["Sunken Treasure"] = true,
	["Timeless Chest"] = true,
	["Conspicuously Empty Shell"] = true,
	---
	["completed"] = "Done",
	["missing"] = "Need",
}
)