local addonName, BBC = ...

if GetLocale() == "frFR" then
	BBC.updateLocale(
{
	["Going To Need A Bigger Bag"] = "Je vais avoir besoin d’un plus gros bagage",
	--
	["Cursed Swabby Helmet"] = "Casque de mousse maudit",
	["Warped Warning Sign"] = "Panneau d’avertissement déformé",
	["Giant Purse of Timeless Coins"] = "Porte-monnaie géant de pièces du Temps figé",
	["Crystal of Insanity"] = "Cristal de démence",
	["Battle Horn"] = "Cor de bataille",
	["Elixir of Ancient Knowledge"] = "Elixir de savoir antique",
	["Forager's Gloves"] = "Gants de fourrageur",
	["Big Bag of Herbs"] = "Grand sac d’herbes",
	["Big Bag of Herbs (Old)"] = "Grand sac d’herbes (vieux)",
	["Wilted Lilypad"] = "Nénuphar démesuré",
	["Hardened Shell"] = "Carapace durcie",
	["Bubbling Pi'jiu Brew"] = "Bière frémissante de Pi’jiu",
	["Thick Pi'jiu Brew"] = "Bière épaisse de Pi’jiu",
	["Misty Pi'jiu Brew"] = "Bière brumeuse de Pi’jiu",
	["Warning Sign"] = "Panneau d’avertissement",
	["Ash-Covered Horn"] = "Corne couverte de cendres",
	["Cauterizing Core"] = "Noyau de cautérisation",
	["Captain Zvezdan's Lost Leg"] = "Jambe perdue du capitaine Zvezdan",
	["Cursed Talisman"] = "Talisman maudit",
	["Golden Moss"] = "Mousse dorée",
	["Strange Glowing Mushroom"] = "Etrange champignon luminescent",
	["Eternal Kiln"] = "Four éternel",
	["Jadefire Spirit"] = "Esprit jadefeu",
	["Sunset Stone"] = "Pierre du couchant",
	["Ashen Stone"] = "Pierre de cendres",
	["Blizzard Stone"] = "Pierre de blizzard",
	["Rain Stone"] = "Pierre à pluie",
	["Blackflame Daggers"] = "Dagues de la flamme noire",
	["Falling Flame"] = "Chute de flammes",
	["Ordon Death Chime"] = "Carillon de la mort d’Ordos",
	["Blazing Sigil of Ordos"] = "Cachet flamboyant d’Ordos",
	["Ordon Ceremonial Robes"] = "Robe de cérémonie ordonne",
	["Rime of the Time-Lost Mariner"] = "Complainte du marin au temps figé",
	["Scuttler's Shell"] = "Conque de carapateur",
	["Partially-Digested Meal"] = "Repas partiellement digéré",
	["Swarmling of Gu'chi"] = "Couvelin de Gu’chi",
	["Sticky Silkworm Goo"] = "Bave collante de ver à soie",
	["Faintly-Glowing Herb"] = "Herbe faiblement luisante",
	["Condensed Jademist"] = "Brumejade condensée",
	["Windfeather Plume"] = "Plume de plumevent",
	["Quivering Firestorm Egg"] = "Oeuf tempête-de-feu tremblant",
	["Reins of the Thundering Onyx Cloud Serpent"] = "Rênes de serpent-nuage d’onyx fulminant",
	["Pristine Stalker Hide"] = "Peau de traqueur en parfait état",
	["Glinting Pile of Stone"] = "Tas de pierres luisantes",
	["Odd Polished Stone"] = "Etrange pierre polie",
	["Glowing Blue Ash"] = "Cendre bleue luminescente",
	["Glowing Green Ash"] = "Cendre verte luminescente",
	["Bonkers"] = "Foldingue",
	["Gulp Froglet"] = "Jeune grenouille gobeuse",
	["Spineclaw Crab"] = "Crabe pincépine",
	["Skunky Alemental"] = "Elémenbière puant",
	["Ominous Flame"] = "Flamme inquiétante",
	["Jademist Dancer"] = "Danseur brumejade",
	["Death Adder Hatchling"] = "Jeune aspic mortel",
	["Dandelion Frolicker"] = "Jonquille boute-en-train",
	["Ruby Droplet"] = "Gouttelette rubis",
	["Azure Crane Chick"] = "Gruon azur",
	["Ashleaf Spriteling"] = "Petit lutin feuille-d’orne",
	---
	["Crane Nest"] = "Nid de grues",
	["Eerie Crystal"] = "Cristal sinistre",
	["Sunken Treasure"] = "Trésor englouti",
	["Timeless Chest"] = "Coffre intemporel",
	["Conspicuously Empty Shell"] = true, -- @TODO: Get translation
	---
	["missing"] = "incomplet",
	["completed"] = "terminé",
}
)

end