local addonName, BBC = ...

if GetLocale() == "ruRU" then
	BBC.updateLocale(
{
	["Going To Need A Bigger Bag"] = "А сумка могла бы быть и побольше",
	--
	["Cursed Swabby Helmet"] = "Проклятый шлем юнги",
	["Warped Warning Sign"] = "Старый предупредительный знак",
	["Giant Purse of Timeless Coins"] = "Огромный кошелек с вневременными монетами",
	["Crystal of Insanity"] = "Кристалл безумия",
	["Battle Horn"] = "Боевой рог",
	["Elixir of Ancient Knowledge"] = "Эликсир древнего знания",
	["Forager's Gloves"] = "Перчатки добытчика",
	["Big Bag of Herbs"] = "Большой мешок трав",
	["Big Bag of Herbs (Old)"] = "Большой мешок трав (прежний)",
	["Wilted Lilypad"] = "Разросшаяся кувшинка",
	["Hardened Shell"] = "Укрепленный панцирь",
	["Bubbling Pi'jiu Brew"] = "Пенящийся отвар Пи'джоу",
	["Thick Pi'jiu Brew"] = "Густой отвар Пи'джоу",
	["Misty Pi'jiu Brew"] = "Туманный отвар Пи'джоу",
	["Warning Sign"] = "Предупредительный знак",
	["Ash-Covered Horn"] = "Покрытый пеплом рог",
	["Cauterizing Core"] = "Прижигающее ядро",
	["Captain Zvezdan's Lost Leg"] = "Утраченная нога капитана Звездана",
	["Cursed Talisman"] = "Проклятый талисман",
	["Golden Moss"] = "Золотой мох",
	["Strange Glowing Mushroom"] = "Странный светящийся гриб",
	["Eternal Kiln"] = "Вечный обжигающий огонь",
	["Jadefire Spirit"] = "Дух нефритового пламени",
	["Sunset Stone"] = "Закатный камень",
	["Ashen Stone"] = "Пепельный камень",
	["Blizzard Stone"] = "Камень снежной бури",
	["Rain Stone"] = "Дождевой камень",
	["Blackflame Daggers"] = "Кинжалы Черного Пламени",
	["Falling Flame"] = "Падающее пламя",
	["Ordon Death Chime"] = "Ордосский смертный колокол",
	["Blazing Sigil of Ordos"] = "Пылающая печать Ордоса",
	["Ordon Ceremonial Robes"] = "Ордосские церемониальные одеяния",
	["Rime of the Time-Lost Mariner"] = "Сказание о затерянном во времени мореходе",
	["Scuttler's Shell"] = "Крабий панцирь",
	["Partially-Digested Meal"] = "Полупереваренная пища",
	["Swarmling of Gu'chi"] = "Роевик Гу'чи",
	["Sticky Silkworm Goo"] = "Липкие экскременты шелкопряда",
	["Faintly-Glowing Herb"] = "Нетронутая шкура охотника",
	["Condensed Jademist"] = "Густой нефритовый туман",
	["Windfeather Plume"] = "Ветроперый плюмаж",
	["Quivering Firestorm Egg"] = "Дрожащее яйцо огненной бури",
	["Reins of the Thundering Onyx Cloud Serpent"] = "Поводья грозового ониксового облачного змея",
	["Pristine Stalker Hide"] = "Нетронутая шкура охотника",
	["Glinting Pile of Stone"] = "Блестящая груда камней",
	["Odd Polished Stone"] = "Странный отполированный камень",
	["Glowing Blue Ash"] = "Мерцающий синий пепел",
	["Glowing Green Ash"] = "Мерцающий зеленый пепел",
	["Bonkers"] = "Сумасброд",
	["Gulp Froglet"] = "Юная хваткая лягушка",
	["Spineclaw Crab"] = "Краб-хребтохват",
	["Skunky Alemental"] = "Прокисший хмелементаль",
	["Ominous Flame"] = "Зловещее пламя",
	["Jademist Dancer"] = "Танцор из нефритовых туманов",
	["Death Adder Hatchling"] = "Детеныш смертолаза",
	["Dandelion Frolicker"] = "Одуванчиковая резвунья",
	["Ruby Droplet"] = "Рубиновая капля",
	["Azure Crane Chick"] = "Птенец лазурного журавля",
	["Ashleaf Spriteling"] = "Малый дух ясеневого листа",
	---
	["Crane Nest"] = "Журавлиное гнездо",
	["Eerie Crystal"] = "Зловещий кристалл",
	["Sunken Treasure"] = "Затонувшее сокровище",
	["Timeless Chest"] = "Вневременный сундук",
	["Conspicuously Empty Shell"] = true, -- @TODO: Get translation
	----
	["missing"] = "неполный",
	["completed"] = "завершено: ",
}
)

end