-- Credit to user xy985426 from CurseForge for this translation.

if GetLocale() == "zhCN" then
	updateLocale(
{
	["Going To Need A Bigger Bag"] = "需要一个大背包",
	--
	["Cursed Swabby Helmet"] = "受诅咒的水手头盔",
	["Warped Warning Sign"] = "扭曲的警告标志",
	["Giant Purse of Timeless Coins"] = "一大包永恒铸币",
	["Crystal of Insanity"] = "狂乱水晶",
	["Battle Horn"] = "战斗号角",
	["Elixir of Ancient Knowledge"] = "远古知识药剂",
	["Forager's Gloves"] = "劫匪的手套",
	["Big Bag of Herbs"] = "一大袋草药",
	["Big Bag of Herbs (Old)"] = "一大袋草药(旧)",
	["Wilted Lilypad"] = "过度生长的睡莲",
	["Hardened Shell"] = "硬化之壳",
	["Bubbling Pi'jiu Brew"] = "气泡老啤酒",
	["Thick Pi'jiu Brew"] = "馥郁老啤酒",
	["Misty Pi'jiu Brew"] = "薄雾老啤酒",
	["Warning Sign"] = "警告标志",
	["Ash-Covered Horn"] = "蒙尘号角",
	["Cauterizing Core"] = "炽灼之核",
	["Captain Zvezdan's Lost Leg"] = "扎维兹坦船长遗失的小腿",
	["Cursed Talisman"] = "被诅咒的护符",
	["Golden Moss"] = "金苔藓",
	["Strange Glowing Mushroom"] = "发光的怪蘑菇",
	["Eternal Kiln"] = "永恒炭炉",
	["Jadefire Spirit"] = "玉火焰灵",
	["Sunset Stone"] = "夕阳之石",
	["Ashen Stone"] = "灰烬之石",
	["Blizzard Stone"] = "风雪之石",
	["Rain Stone"] = "降雨之石",
	["Blackflame Daggers"] = "黑火匕首",
	["Falling Flame"] = "坠落之焰",
	["Ordon Death Chime"] = "斡耳朵死亡之钟",
	["Blazing Sigil of Ordos"] = "斡耳朵斯的炽燃之印",
	["Ordon Ceremonial Robes"] = "斡耳朵仪式长袍",
	["Rime of the Time-Lost Mariner"] = "迷时水手结晶",
	["Scuttler's Shell"] = "钳爪蟹壳",
	["Partially-Digested Meal"] = "消化了一半的肉",
	["Swarmling of Gu'chi"] = "古赤的蚕宝宝",
	["Sticky Silkworm Goo"] = "黏糊糊的蚕虫黏液",
	["Faintly-Glowing Herb"] = "微微发光的草药",
	["Condensed Jademist"] = "浓缩的翠雾",
	["Windfeather Plume"] = "风翎鹤羽",
	["Quivering Firestorm Egg"] = "颤动的风火龙蛋",
	["Reins of the Thundering Onyx Cloud Serpent"] = "雷霆玛瑙云端翔龙缰绳",
	["Pristine Stalker Hide"] = "新鲜的追猎者之皮",
	["Glinting Pile of Stone"] = "一堆闪亮的石头",
	["Odd Polished Stone"] = "古怪的抛光石",
	["Glowing Blue Ash"] = "发光的蓝色灰烬",
	["Glowing Green Ash"] = "发光的绿色灰烬",
	["Bonkers"] = "邦卡斯",
	["Gulp Froglet"] = "幼年巨口蛙",
	["Spineclaw Crab"] = "钳爪小螃蟹",
	["Skunky Alemental"] = "酒灵臭臭",
	["Ominous Flame"] = "不祥焰灵",
	["Jademist Dancer"] = "翠雾舞者",
	["Death Adder Hatchling"] = "致死小蝰蛇",
	["Dandelion Frolicker"] = "菊苣嬉闹者",
	["Ruby Droplet"] = "红玉小水滴",
	["Azure Crane Chick"] = "天青雏鹤",
	["Ashleaf Spriteling"] = "灰叶小林精",
	---
	["Crane Nest"] = "鹤巢",
	["Eerie Crystal"] = "神秘的水晶",
	["Sunken Treasure"] = "沉没的宝箱",
	["Timeless Chest"] = "永恒宝箱",
	["Conspicuously Empty Shell"] = true, -- @TODO: Get translation
	---
	["missing"] = "缺少",
	["completed"] = "已完成",
}
)

end
