
if GetLocale() == "zhTW" then
	updateLocale(
{
	["Going To Need A Bigger Bag"] = "需要更大的袋子",
	--
	["Cursed Swabby Helmet"] = "受詛咒的潛水者頭盔",
	["Warped Warning Sign"] = "歪斜的警告標誌",
	["Giant Purse of Timeless Coins"] = "永恆硬幣大型錢袋",
	["Crystal of Insanity"] = "精神錯亂水晶",
	["Battle Horn"] = "戰鬥號角",
	["Elixir of Ancient Knowledge"] = "遠古知識藥劑",
	["Forager's Gloves"] = "強奪者手套",
	["Big Bag of Herbs"] = "一大袋藥草",
	["Big Bag of Herbs (Old)"] = "一大袋藥草(舊)",
	["Wilted Lilypad"] = "巨大的睡蓮葉",
	["Hardened Shell"] = "強化硬殼",
	["Bubbling Pi'jiu Brew"] = "泡沫老埤周啤酒",
	["Thick Pi'jiu Brew"] = "濃醇老埤周啤酒",
	["Misty Pi'jiu Brew"] = "混濁老埤周啤酒",
	["Warning Sign"] = "警告標誌",
	["Ash-Covered Horn"] = "覆著灰燼的角",
	["Cauterizing Core"] = "灼焚之核",
	["Captain Zvezdan's Lost Leg"] = "船長伊斯斐丹的斷腿",
	["Cursed Talisman"] = "被詛咒的咒符",
	["Golden Moss"] = "黃金苔",
	["Strange Glowing Mushroom"] = "奇怪的發光蘑菇",
	["Eternal Kiln"] = "永恆窯爐",
	["Jadefire Spirit"] = "碧火精靈",
	["Sunset Stone"] = "日落之石",
	["Ashen Stone"] = "塵暴之石",
	["Blizzard Stone"] = "暴雪之石",
	["Rain Stone"] = "暴雨之石",
	["Blackflame Daggers"] = "黑焰匕首",
	["Falling Flame"] = "流火之焰",
	["Ordon Death Chime"] = "歐朵獻祭風鈴",
	["Blazing Sigil of Ordos"] = "歐朵斯熾火法印",
	["Ordon Ceremonial Robes"] = "歐朵儀祭長袍",
	["Rime of the Time-Lost Mariner"] = "驚懼水手之歌",
	["Scuttler's Shell"] = "螃蟹殼",
	["Partially-Digested Meal"] = "消化了一半的餐食",
	["Swarmling of Gu'chi"] = "古奇的蟲群",
	["Sticky Silkworm Goo"] = "蠶的黏液",
	["Faintly-Glowing Herb"] = "閃著微光的藥草",
	["Condensed Jademist"] = "凝結碧霧",
	["Windfeather Plume"] = "風鶴之雨",
	["Quivering Firestorm Egg"] = "顫動的火焰風暴之蛋",
	["Reins of the Thundering Onyx Cloud Serpent"] = "雷霆黑曜雲蛟韁繩",
	["Pristine Stalker Hide"] = "原始潛獵者皮革",
	["Glinting Pile of Stone"] = "一堆閃爍的石頭",
	["Odd Polished Stone"] = "光滑的怪石子",
	["Glowing Blue Ash"] = "發光的藍色灰燼",
	["Glowing Green Ash"] = "發光的綠色灰燼",
	["Bonkers"] = "嚎怪",
	["Gulp Froglet"] = "小咕嚕蛙",
	["Spineclaw Crab"] = "虎鉗蟹",
	["Skunky Alemental"] = "惡臭酒元素",
	["Ominous Flame"] = "不祥之焰",
	["Jademist Dancer"] = "碧霧舞者",
	["Death Adder Hatchling"] = "死亡奎蛇寶寶",
	["Dandelion Frolicker"] = "蒲公英小妖",
	["Ruby Droplet"] = "小晶紅水靈",
	["Azure Crane Chick"] = "小蒼藍鶴",
	["Ashleaf Spriteling"] = "小灰葉妖精",
	---
	["Crane Nest"] = "鶴巢",
	["Eerie Crystal"] = "神秘的水晶",
	["Sunken Treasure"] = "水下寶藏",
	["Timeless Chest"] = "永恆寶箱",
	----
	["missing"] = "缺少",
	["completed"] = "已完成",
}
)

end